apiVersion: v1
kind: Service
metadata:
  name: multi-port-service
spec:
  type: NodePort  # Exposes the service internally in the cluster
  selector:
    app: multi-port-app
  ports:
  - name: http
    protocol: TCP
    port: 80        # Port exposed by the service
    targetPort: 80  # Port on the container
  - name: https
    protocol: TCP
    port: 443       # Port exposed by the service
    targetPort: 443 # Port on the container

